# secret
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_ROOT_PASSWORD: cm9vdA==    # base64("root")
  DB_USERNAME: b3JkZXJ1c2Vy    # base64("orderuser")
  DB_PASSWORD: b3JkZXJwYXNz    # base64("orderpass")
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_USER: Z3Vlc3Q=       # base64("guest")
  RABBITMQ_PASSWORD: Z3Vlc3Q=   # base64("guest")

## 커밋 테스트용